apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-v1
  labels: 
    app: vproapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      version: vproapp-v1
  template:
    metadata:
      labels:
        app: vproapp
        version: vproapp-v1
    spec:
      containers:
      - name: vproapp
        image: richardxgf/vprofileapp:1.0.0
        ports:
        - name: vproapp-port
          containerPort: 8080
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
