apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc-v1
  labels:
    app: vpromc-v1
spec:
  selector:
    matchLabels:
      version: vpromc-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromc
        version: vpromc-v1
    spec:
      containers:
      - name: vpromc
        image: memcached
        ports:
        - name: vpromc-port
          containerPort: 11211
